@startuml
client -> Creator: anOperation()
Creator -> ConcreteCreator: factoryMethod()
ConcreteCreator --> ConcreteProduct: new ConcreteProduct()
Creator <-- ConcreteCreator
client <-- Creator
@enduml